name: pudl-rmi
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab~=3.0
  - pip~=20.3
  - python>=3.8
  - pandas>=1.2
  - numpy~=1.19
  - scikit-learn~=0.24
  - seaborn~=0.11.1
  - fuzzywuzzy
  - addfips~=0.3.0
  - catalystcoop.dbfread~=3.0
  - coloredlogs~=15.0
  - contextily~=1.0
  - datapackage~=1.11
  - geopandas~=0.8.1
  - goodtables-pandas-py~=0.2.0
  - google-cloud-storage~=1.35.0
  - matplotlib~=3.0
  - networkx~=2.2
  - numpy~=1.19
  - pandas~=1.2
  - prefect[viz, gcp]~=0.14.2
  - pyarrow~=2.0
  - pyyaml~=5.0
  - scikit-learn~=0.24
  - scipy~=1.6
  - seaborn~=0.11.1
  - sqlalchemy~=1.3
  - tableschema~=1.12
  - tableschema-sql~=1.3
  - timezonefinder~=5.0
  - tqdm~=4.0
  - xlsxwriter~=1.3
  - xlrd
  - fuzzywuzzy
  - pip:
    - git+https://github.com/catalyst-cooperative/pudl.git@rmi_pudl
    - recordlinkage~=0.14.0
