name: pudl-rmi
channels:
  - conda-forge
  - defaults
dependencies:
  - pip~=21.0
  - python~=3.8

  # PUDL dependencies
  - addfips~=0.3.0
  - catalystcoop.dbfread~=3.0
  - coloredlogs~=15.0
  - contextily~=1.0
  - datapackage~=1.11
  - fsspec~=0.8.5
  - gcsfs~=0.7.1
  - geopandas~=0.8.1
  - goodtables-pandas-py~=0.2.0
  - google-cloud-storage~=1.35
  - google-cloud-bigquery~=1.28
  - matplotlib~=3.0
  - networkx~=2.2
  - numpy~=1.20
  - pandas~=1.2
  - prefect~=0.14.2
  - pyarrow~=3.0
  - pyyaml~=5.0
  - python-snappy~=0.6.0
  - scikit-learn~=0.24
  - scipy~=1.6
  - seaborn~=0.11.1
  - sqlalchemy~=1.3
  - tableschema~=1.12
  - tableschema-sql~=1.3
  - timezonefinder~=5.0
  - tqdm~=4.0
  - xlsxwriter~=1.3

  # User / RMI Packages
  - jupyterlab~=3.0
  - jupyter-resource-usage~=0.5.0
  - nbgitpuller~=0.9
  - fuzzywuzzy

  - pip:
    - git+https://github.com/catalyst-cooperative/pudl.git@pudl-rmi
    - recordlinkage~=0.14.0
    - jupyter-offlinenotebook~=0.2
    - --editable ./
