name: pudl-rmi
channels:
  - conda-forge
  - defaults
dependencies:
  # Basic python environment requirements:
  - pip>=22,<23
  - python>=3.8,<3.11
  - setuptools<62

  # Tricky binary dependencies, best resolved w/ conda:
  - geopandas>=0.9,<0.11
  - pygeos>=0.10,<0.13
  - python-snappy>=0.6,<1  # Ensures snappy-dev library gets installed
  - numba>=0.55.1,<0.56  # not strictly necessary, but speeds some things up by 100x
  - sqlite>=3.36,<4   # Required by PUDL 0.5.0 and later.

  # So we can run a notebook server
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage>=0.5,<1

  # Visualization and data validation packages used interactively but not required.
  - pandera~=0.7.2
  - seaborn~=0.11.2
  - plotly==5.4.0

  # Not normal Python packages that come from PyPI
  - nodejs  # Useful for Jupyter Notebook Server

  - pip:
    - simpledbf~=0.2.6
    # Install the (local) pudl_rmi package such that we can do development work:
    - --editable ./[test]
    # If you want to be able to make changes to the PUDL repo as well, you can install
    # it in editable mode with a line like the following. HOWEVER if you do that, you
    # MUST remove or comment out the github based dependency inside setup.py as
    # it will supersede the editable installation:
    # - --editable ../path/to/your/cloned/pudl/repo
