[build-system]
requires = ["setuptools<60.0.0", "pip", "wheel"]

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
known_first_party = "pudl_rmi"
